export enum EQuoteTheme {
  DARK = 'dark',
  CHARTREUSE_DARK = 'chartreuse-dark',
  RADICAL = 'radical',
  MERKO = 'merko',
  GRUVBOX = 'gruvbox',
  CATPPUCCIN_LATTE = 'catppuccin_latte',
  CATPPUCCIN_FRAPPE = 'catppuccin_frappe',
  CATPPUCCIN_MACCHIATO = 'catppuccin_macchiato',
  CATPPUCCIN_MOCHA = 'catppuccin_mocha',
  TOKYONIGHT = 'tokyonight',
  ALGOLIA = 'algolia',
  MONOKAI = 'monokai',
  DRACULA = 'dracula',
  NORD = 'nord',
}

export enum EQuoteType {
  VERTICAL = 'vertical',
  HORIZONTAL = 'horizontal',
}

export enum EJokeTheme {
  DEFAULT = 'default',
  GRADIENT_BLUE = 'gradientBlue',
  SOLID_BLUE = 'solidBlue',
  HALLOWEEN = 'halloween',
  WATERMELON = 'watermelon',
  PINKISH = 'pinkish',
  DAY_SKY = 'daySky',
  RADICAL = 'radical',
  MERKO = 'merko',
  GRUVBOX = 'gruvbox',
  TOKYONIGHT = 'tokyonight',
  ONEDARK = 'onedark',
  COBALT = 'cobalt',
  SYNTHWAVE = 'synthwave',
  DRACULA = 'dracula',
  PRUSSIAN = 'prussian',
  MONOKAI = 'monokai',
  VUE = 'vue',
  VUE_DARK = 'vue-dark',
  NIGHTOWL = 'nightowl',
  BUEFY = 'buefy',
  BLUE_GREEN = 'blue-green',
  ALGOLIA = 'algolia',
  DARCULA = 'darcula',
  BEAR = 'bear',
  SOLARIZED_DARK = 'solarized-dark',
  SOLARIZED_LIGHT = 'solarized-light',
  GOHAM = 'gotham',
  MATERIAL_PALENIGHT = 'material-palenight',
  GRAYWHITE = 'graywhite',
  AYU_MIRAGE = 'ayu-mirage',
  CALM = 'calm',
  FLAG_INDIA = 'flag-india',
  OMNI = 'omni',
  REACT = 'react',
  BLUEBERRY = 'blueberry',
  RANDOM = 'random',
}

export enum EQuoteProvider {
  QUOTE = 'quote',
  QUOTE_JOKES = 'quote jokes',
}
