export enum EProvider {
  STATS = 'statitics',
  LANGUAGES = 'languages',
}

export enum EGithubReadmeStatsTheme {
  DEFAULT = 'default',
  TRANSPARENT = 'transparent',
  SHADOW_RED = 'shadow_red',
  SHADOW_GREEN = 'shadow_green',
  SHADOW_BLUE = 'shadow_blue',
  DARK = 'dark',
  RADICAL = 'radical',
  MERKO = 'merko',
  GRUVBOX = 'gruvbox',
  GRUVBOX_LIGHT = 'gruvbox_light',
  TOKYONIGHT = 'tokyonight',
  ONEDARK = 'onedark',
  COBALT = 'cobalt',
  SYNTHWAVE = 'synthwave',
  HIGHCONTRAST = 'highcontrast',
  DRACULA = 'dracula',
  PRUSSIAN = 'prussian',
  MONOKAI = 'monokai',
  VUE = 'vue',
  VUE_DARK = 'vue-dark',
  SHADES_OF_PURPLE = 'shades-of-purple',
  NIGHTOWL = 'nightowl',
  BUEFY = 'buefy',
  BLUE_GREEN = 'blue-green',
  ALGOLIA = 'algolia',
  GREAT_GATSBY = 'great-gatsby',
  DARCULA = 'darcula',
  BEAR = 'bear',
  SOLARIZED_DARK = 'solarized-dark',
  SOLARIZED_LIGHT = 'solarized-light',
  CHARTREUSE_DARK = 'chartreuse-dark',
  NORD = 'nord',
  GOTHAM = 'gotham',
  MATERIAL_PALENIGHT = 'material-palenight',
  GRAYWHITE = 'graywhite',
  VISION_FRIENDLY_DARK = 'vision-friendly-dark',
  AYU_MIRAGE = 'ayu-mirage',
  MIDNIGHT_PURPLE = 'midnight-purple',
  CALM = 'calm',
  FLAG_INDIA = 'flag-india',
  OMNI = 'omni',
  REACT = 'react',
  JOLLY = 'jolly',
  MAROONGOLD = 'maroongold',
  YEBLU = 'yeblu',
  BLUEBERRY = 'blueberry',
  SLATEORANGE = 'slateorange',
  KACHO_GA = 'kacho_ga',
  OUTRUN = 'outrun',
  OCEAN_DARK = 'ocean_dark',
  CITY_LIGHTS = 'city_lights',
  GITHUB_DARK = 'github_dark',
  GITHUB_DARK_DIMMED = 'github_dark_dimmed',
  DISCORD_OLD_BLURPLE = 'discord_old_blurple',
  AURA_DARK = 'aura_dark',
  PANDA = 'panda',
  NOCTIS_MINIMUS = 'noctis_minimus',
  COBALT2 = 'cobalt2',
  SWIFT = 'swift',
  AURA = 'aura',
  APPRENTICE = 'apprentice',
  MOLTACK = 'moltack',
  CODESTACKR = 'codeSTACKr',
  ROSE_PINE = 'rose_pine',
  CATPPUCCIN_LATTE = 'catppuccin_latte',
  CATPPUCCIN_MOCHA = 'catppuccin_mocha',
  DATE_NIGHT = 'date_night',
  ONE_DARK_PRO = 'one_dark_pro',
  ROSE = 'rose',
  HOLI = 'holi',
  NEON = 'neon',
  BLUE_NAVY = 'blue_navy',
  CALM_PINK = 'calm_pink',
  AMBIENT_GRADIENT = 'ambient_gradient',
}

export enum EHideStats {
  STARS = 'stars',
  COMMITS = 'commits',
  PRS = 'prs',
  ISSUES = 'issues',
  CONTRIBS = 'contribs',
}

export enum EAdditionStats {
  REVIEWS = 'reviews',
  DISCUSSIONS_STARTED = 'discussions_started',
  DISCUSSIONS_ANSWERED = 'discussions_answered',
  PRS_MERGED = 'prs_merged',
  PRS_MERGED_PERCENTAGE = 'prs_merged_percentage',
}

export enum ERankIcon {
  DEFAULT = 'default',
  GITHUB = 'github',
  PERCENTILE = 'percentile',
}

export enum ELanguageLayout {
  DEFAULT = 'default',
  COMPACT = 'compact',
  DONUT = 'donut',
  DONUT_VERTICAL = 'donut-vertical',
  PIE = 'pie',
}
